Add possibility to customize special button behaviour
konaire/NumericKeyboard pull request #4
Opened 2018-12-24 11:51 UTC by paolorotolo

2019-01-22 23:15 UTC, konaire requested changes
Sorry for the late reply. Amazing job 🏄‍♂️Just a few small comments and good to go.

2019-01-22 23:15 UTC, konaire commented on app/src/main/java/com/konaire/sample/MainActivity.kt
> +        */
Those comment lines shouldn't be here. By default `MainActivity` displays only simple keyboard. It would be great if you'll add it to the README. And also please remove redundant import lines.

2019-01-22 23:15 UTC, konaire commented on numeric-keyboard/src/main/java/com/konaire/numerickeyboard/NumericKeyboard.kt
> +            keySpecial.isEnabled = true
```suggestion
            keySpecial.isEnabled = keySpecialText.isNotEmpty()
```

and remove if of course

2019-01-22 23:15 UTC, konaire commented on numeric-keyboard/src/main/java/com/konaire/numerickeyboard/NumericKeyboard.kt
> +            keySpecial.setOnClickListener(keySpecialListener)
You could simplify it like this:
```suggestion
            keySpecial.setOnClickListener(keySpecialListener ?: listener)
```

2019-01-22 23:15 UTC, konaire commented on numeric-keyboard/src/main/java/com/konaire/numerickeyboard/NumericKeyboard.kt
> +    fun onKeySpecialClick(function: (() -> Unit)) {
This method is overkill. You can just use lambda if you want to add a custom listener, right?

2019-01-23 09:28 UTC, paolorotolo commented
Changes applied. Please review again and merge.

2019-01-23 09:29 UTC, paolorotolo commented
Also Gradle version has been updated to ```3.3.0```.

2019-01-24 19:12 UTC, konaire approved these changes
Nice work 👍

2019-01-24 19:13 UTC, merged